### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by marklester** [rxlabz/flutter-mediaplayer-plugin#1]
Can you add to the readme how to use this?
How to install is the main thing I am not getting from the readme right now

**Comment by rxlabz** [comment]
@marklester sure :). Something like this ?

```bash
git clone
cd flutter-media-plugin
flutter packages get
flutter doctor
# after following all doctor's instructions
flutter run -d YOUR_DEVICE
```

**Comment by marklester** [comment]
So you can't add as is to an existing flutter app?

**Comment by rxlabz** [comment]
not really 🙁 . It's just a simple sample to verify the faisability, not ready for distribution. For now the name of the project should better be media player-poc, rather than plugin.
But that said, reusing the java and objc classes by copying them in your project should be relatively easy.
Basically I just started from the Flutter platformMessage example, and added few functions, and a videoActivity for both iOS and java.
Warning :  I am neither a java nor objc dev, so I'm not sure I did it in the best possible way :).

**Comment by tjerkw** [comment]
Nice work, we should make this a real flutter plugin so others can also use it in their flutter app.

**Comment by rxlabz** [comment]
thanks @tjerkw , I started https://github.com/rxlabz/flutter_audio , but I didn't found swift plugin example, and my ObjC skills are too limited... so it's kind of "paused" for now

**Comment by rxlabz** [comment]
finally an updated audio plugin : https://github.com/rxlabz/audioplayer & video plugin : https://github.com/rxlabz/video_launcher
